### ISSUE TITLE
Anova Test for Binary Sheep/Dog Variable vs. Dog Detection Rate

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/bobcats_conflict#3]
https://github.com/LaraVolski/bobcats_conflict/blob/85773ad097832e4730d0e83ccb73cdb6cc54165c/LGD_Models2.rmd#L48

The binary 'Sheep' variable is just a Y or N when sheep were detected by a camera trap. Since LGDs were often present whenever sheep were present, this can also provide insight into how bobcats respond to dogs. Then there's also the DOG_RAI measure of dog presence. I want to do an anova test to see which one more meaningfully impacts bobcat activity. But I'm unsure of how to go about this.

**Comment by kaitlyngaynor** [comment]
I wouldn't do an ANOVA test—I would just do model comparison. Does the model with Sheep (Model3) or the model with DOG_RAI (Model2) give you a lower AIC? Whichever has lower AIC has more support, and if their AIC values are within ~2, they can be said to have roughly equal support.

**Comment by LaraVolski** [comment]
hehe somehow I always make up ways to make more work for myself. thanks Kaitlyn!
