### ISSUE TITLE
Failure to converge

### ISSUE THREAD

**Issue by LaraVolski** [LaraVolski/bobcats_conflict#6]
https://github.com/LaraVolski/bobcats_conflict/blob/c14c72170fcef4a48114ee2ce544130d6713bc34/LGD_Models_UsingNB.rmd#L41

Could I get your advice as to how to rescale these variables/address the failure to converge here? 

If it gives me this warning, but still runs the model... is a failure to converge an issue?

**Comment by kaitlyngaynor** [comment]
Can you point me to the line where you create Dogs_Scaled? I don't see how you are scaling—are you just using the scale() function?

Can you copy the warning message here?

Failure to converge IS an issue, you can't really trust what those models say

**Comment by LaraVolski** [comment]
I manually scaled them by doing (value - mean)/(st. dev) for each row. So if there was 1 individual dog counted for that pasture, I did: (1 - mean(subset.rai$Individual_Dog) / sd(subset.rai$Individual_Dog). 

The failure to converge warning message says: 

Warning: Model failed to converge with max|grad| = 0.0522747 (tol = 0.002, component 1)Warning: Model is nearly unidentifiable: very large eigenvalue
 - Rescale variables?

**Comment by kaitlyngaynor** [comment]
https://groups.google.com/g/unmarked/c/n5nkaDs6Xus

**Comment by LaraVolski** [comment]
Adding control=glmerControl(optimizer="bobyqa") fixed the convergence error :)

**Comment by kaitlyngaynor** [comment]
ahhhhh yes I have previously found and used this solution to this same error, hah! glad you figured it out
